export default function Home() {
  return (
    <>
      <img src="https://i.postimg.cc/59SRVjCz/891233042e9ada9873fc6d9c4e835eac.jpg" class="rounded-lg w-full md:w1/2 mx-auto my-4"/>
      <main class= "text-center text-2xl font-bold mb-4 underline text-green-700">Biryani Scene Of New York (Part One)</main>
      <h1 class= "italic text-green-700">I have started writing about biryani in a medium today thinking it's been about 15 weeks. But my fascination with biryani dates back much earlier. The fact that this extraordinary and beautiful dish has become a signature dish of the Indian subcontinent has always fascinated me. My journey in search of biryani's secrets has always excited me. It's the enthusiasm and courage I've received from the readers and writers of the medium during this journey that is unparalleled.</h1>
      <h2 class= "italic text-green-700">I am a Dhaka boy. Dhaka is the capital city of Bangladesh, a small but densely populated country of South Asia. What I've eaten as biryani, I've learned it in the lanes of Old Dhaka, and I can say that I've discovered biryani as a food or the sweetness of biryani right in the streets of Dhaka. In the era of globalization, Cuisine from other countries has become easily accessible, and my acquaintances with various types of biryani have expanded. But at the end of the day, Dhaka's biryani has a special place in my heart, and today I will write about Dhaka's biryani.</h2>
      <main class= "text-center text-2xl font-bold mb-4 underline text-purple-700">My Journry Start </main>
      <h3 class= "italic  text-purple-700 ">I am presenting the story of Dhaka's biryani to you in three parts. I know that I've been writing about biryani for the past three months, and you might wonder why I need such a long three-part mini-series about Dhaka's biryani. However, Dhaka's biryani holds a special place in my heart, and I do not feel even a hint of shame in saying that. So, stay with me, and welcome to the world of Dhaka's biryani.</h3>
<h4 class= "italic  text-purple-700">In our country, especially in old Dhaka, Kacchi Biryani is the most popular. The word "Kacchi" comes from the Urdu word "Kachha," which means raw. Since it is cooked directly with fragrant rice and meat, it is called "Kacchi." This name is known in Hindi and Urdu as well. Besides, it is prepared by mixing marinated meat with rice, potatoes, and condiments, making it Pakki Biryani.</h4>

<h5 class= "italic mb-4  text-purple-700">Both Pulao and Biryani are made with fragrant rice and meat. However, there are significant differences between them. In our country, whether we put meat in Pulao is optional. However, in Biryani, meat is a crucial ingredient. Additionally, Pulao's origin is in Central Asia. In that region, Pulao is cooked with meat. Even in India and Pakistan, Pulao is often prepared in a similar manner. The Mughals were from Central Asia, and they brought Pulao's culture with them. However, the main difference between Pulao and Biryani lies in the extensive use of spices in Biryani. Biryani uses a wide variety of spices in large quantities compared to Pulao, making Biryani's flavors much more intense. </h5>
<main class= "text-center text-2xl font-bold mb-4 underline  text-red-700">Diverse Area </main>
<h6 class= "italic  text-red-700 ">If you go to Uzbekistan or Turkmenistan in Central Asia today, you will see the original forms of Pulao and Biryani. However, what's interesting is that we, the people of the Indian subcontinent, are so accustomed to using a wide variety of spices that the original Pulao in Samarkand or Bukhara seems rather plain to us. At least those who have tasted both have mostly said the same thing. However, another significant difference between Pulao and Biryani is in their fundamental cooking techniques. In Pulao, rice is soaked in water for some time before cooking and then boiled in water. But in Biryani, rice is not soaked and washed extensively.</h6>
<h7 class= "italic  text-red-700">Tehari is a special variation of Biryani. In Tehari, the quantity of meat is less, and there are more potatoes and bones. Mainly, during the Second World War, due to the high price of meat, this diversity was introduced to save costs. However, even though the circumstances have changed, Tehari has not. In Kashmir, Tehari is a very popular street food.</h7>
<h7 class= "italic  text-red-700">Tehari is a special variation of Biryani. In Tehari, the quantity of meat is less, and there are more potatoes and bones. Mainly, during the Second World War, due to the high price of meat, this diversity was introduced to save costs. However, even though the circumstances have changed, Tehari has not. In Kashmir, Tehari is a very popular street food.</h7>
<h8 class= "italic text-red-700 ">If we talk about the trademark of Dhaka city, without a doubt, Dhaka's Kacchi Biryani will be one of the first things to be chosen. Whether it's a wedding or any social event, a gathering of friends, or a reunion, wherever there's an arrangement for a grand feast, Biryani must not be left behind. Mainly, the city of Dhaka was influenced by various Mughal items, among which Biryani stands out. Dhaka's culinary history is closely linked with the evolution of its street food.</h8>
<h9 class= "italic text-red-700">However, when it comes to Dhaka Biryani's name, undoubtedly, "Haji Biryani" is the name that will come to everyone's mind first. In 1939, Haji Golam Hossen Sahib started this biryani recipe, and the respect for it is still present in the mouths of Dhaka's people. The descendants of Haji Biryani's ownership and its successors have been doing business under this renowned name. If we talk about the success of Haji Biryani, it has inspired different biryani shops in various regions, spreading the art of Dhaka's biryani. In addition to that, Biryani has now spread its influence far and wide in distant lands.In the 400-year history of the Indian subcontinent, Biryani has become so deeply rooted that it would be a mistake to call it just a food item. It is a part of our national identity, present in moments of joy and sorrow, festivals, and celebrations, as well as in many national achievements and challenges. Therefore, Biryani has merged with our national identity, representing our cultural heritage. Dhaka's Biryani can be divided into two main categories: Tehari and Biryani. In the next part, we will discuss Tehari or Pulao-style Biryani. So, stay tuned!</h9>

    </>
  );
}
